import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const InterFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "iL4y",
  description: "Generated by iL4y",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${InterFont.variable} antialiased`}>{children}</body>
    </html>
  );
}
